import React, { useState } from 'react';
import { View, Text, Pressable, ScrollView, Share } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { useSessionStore, useAuthStore } from '@/lib/store';
import { cn } from '@/lib/cn';
import * as Haptics from 'expo-haptics';
import Animated, { FadeInDown, FadeInUp } from 'react-native-reanimated';
import {
  ArrowLeft,
  CheckCircle2,
  AlertTriangle,
  TrendingDown,
  TrendingUp,
  Package,
  ClipboardCheck,
  Send,
  Share2,
  FileText,
  Clock,
  User,
  MapPin,
  BarChart3,
} from 'lucide-react-native';

export default function CheckoutScreen() {
  const router = useRouter();
  const { sessionId } = useLocalSearchParams<{ sessionId: string }>();

  const user = useAuthStore((s) => s.user);
  const sessions = useSessionStore((s) => s.sessions);
  const entries = useSessionStore((s) => s.entries);
  const submitForVerification = useSessionStore((s) => s.submitForVerification);
  const completeSession = useSessionStore((s) => s.completeSession);

  const [isSubmitting, setIsSubmitting] = useState(false);

  const session = sessions.find((s) => s.id === sessionId);
  const sessionEntries = entries.filter((e) => e.sessionId === sessionId);

  if (!session) {
    return (
      <View className="flex-1 bg-slate-900 items-center justify-center">
        <Text className="text-white">Session not found</Text>
      </View>
    );
  }

  // Calculate stats
  const totalItems = sessionEntries.length;
  const shortItems = sessionEntries.filter((e) => e.variance < 0);
  const overItems = sessionEntries.filter((e) => e.variance > 0);
  const matchedItems = sessionEntries.filter((e) => e.variance === 0);

  const totalShortQty = shortItems.reduce((sum, e) => sum + Math.abs(e.variance), 0);
  const totalOverQty = overItems.reduce((sum, e) => sum + e.variance, 0);

  const totalShortValue = shortItems.reduce((sum, e) => sum + Math.abs(e.varianceValue ?? 0), 0);
  const totalOverValue = overItems.reduce((sum, e) => sum + (e.varianceValue ?? 0), 0);
  const netVarianceValue = totalOverValue - totalShortValue;

  const accuracyRate = totalItems > 0
    ? Math.round((matchedItems.length / totalItems) * 100)
    : 0;

  const hasIssues = shortItems.length > 0 || overItems.length > 0;

  const handleSubmitForVerification = async () => {
    if (!session) return;

    setIsSubmitting(true);
    await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);

    submitForVerification(session.id);

    setTimeout(() => {
      setIsSubmitting(false);
      router.dismissAll();
      router.replace('/dashboard');
    }, 500);
  };

  const handleCompleteSession = async () => {
    if (!session) return;

    setIsSubmitting(true);
    await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);

    completeSession(session.id);

    setTimeout(() => {
      setIsSubmitting(false);
      router.dismissAll();
      router.replace('/dashboard');
    }, 500);
  };

  const handleShare = async () => {
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

    const report = `
Stock Verification Summary
==========================
Session: ${session.rackNo}
Location: ${session.locationType}
Date: ${new Date(session.createdAt).toLocaleDateString()}
Counted by: ${session.userName}

Summary:
- Total Items: ${totalItems}
- Matched: ${matchedItems.length} (${accuracyRate}%)
- Short: ${shortItems.length} items (${totalShortQty} units)
- Over: ${overItems.length} items (${totalOverQty} units)

Value Impact:
- Short Value: ₹${totalShortValue.toLocaleString()}
- Over Value: ₹${totalOverValue.toLocaleString()}
- Net Variance: ₹${Math.abs(netVarianceValue).toLocaleString()} ${netVarianceValue >= 0 ? '(Over)' : '(Short)'}

${shortItems.length > 0 ? `
Short Items:
${shortItems.map((e) => `- ${e.itemName}: ${e.variance} (₹${Math.abs(e.varianceValue ?? 0).toLocaleString()})`).join('\n')}
` : ''}
${overItems.length > 0 ? `
Over Items:
${overItems.map((e) => `- ${e.itemName}: +${e.variance} (₹${(e.varianceValue ?? 0).toLocaleString()})`).join('\n')}
` : ''}
---
Generated by Stock Verify App
    `.trim();

    try {
      await Share.share({
        message: report,
        title: `Stock Verification - ${session.rackNo}`,
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  return (
    <View className="flex-1">
      <LinearGradient colors={['#0F172A', '#1E293B']} style={{ flex: 1 }}>
        <SafeAreaView className="flex-1">
          <ScrollView className="flex-1" showsVerticalScrollIndicator={false}>
            <View className="px-6 pt-4 pb-8">
              {/* Header */}
              <View className="flex-row items-center mb-6">
                <Pressable
                  onPress={() => router.back()}
                  className="w-10 h-10 rounded-full bg-white/10 items-center justify-center"
                >
                  <ArrowLeft size={20} color="#fff" />
                </Pressable>
                <View className="ml-4 flex-1">
                  <Text className="text-white font-bold text-xl">Session Checkout</Text>
                  <Text className="text-slate-400 text-sm">{session.rackNo}</Text>
                </View>
                <Pressable
                  onPress={handleShare}
                  className="w-10 h-10 rounded-full bg-white/10 items-center justify-center"
                >
                  <Share2 size={20} color="#fff" />
                </Pressable>
              </View>

              {/* Session Info */}
              <Animated.View
                entering={FadeInDown.duration(400)}
                className="bg-slate-800/50 rounded-2xl p-4 mb-4"
              >
                <View className="flex-row items-center mb-3">
                  <FileText size={18} color="#64748B" />
                  <Text className="text-white font-semibold ml-2">Session Details</Text>
                </View>

                <View className="space-y-2">
                  <View className="flex-row items-center">
                    <MapPin size={14} color="#64748B" />
                    <Text className="text-slate-400 text-sm ml-2">
                      {session.locationType} - {session.rackNo}
                    </Text>
                  </View>
                  <View className="flex-row items-center">
                    <User size={14} color="#64748B" />
                    <Text className="text-slate-400 text-sm ml-2">{session.userName}</Text>
                  </View>
                  <View className="flex-row items-center">
                    <Clock size={14} color="#64748B" />
                    <Text className="text-slate-400 text-sm ml-2">
                      {new Date(session.createdAt).toLocaleString()}
                    </Text>
                  </View>
                </View>
              </Animated.View>

              {/* Accuracy Score */}
              <Animated.View
                entering={FadeInDown.duration(400).delay(50)}
                className={cn(
                  'rounded-2xl p-6 mb-4 items-center',
                  accuracyRate >= 90
                    ? 'bg-green-500/20'
                    : accuracyRate >= 70
                      ? 'bg-amber-500/20'
                      : 'bg-red-500/20'
                )}
              >
                <View
                  className={cn(
                    'w-20 h-20 rounded-full items-center justify-center mb-3',
                    accuracyRate >= 90
                      ? 'bg-green-500/30'
                      : accuracyRate >= 70
                        ? 'bg-amber-500/30'
                        : 'bg-red-500/30'
                  )}
                >
                  {accuracyRate >= 90 ? (
                    <CheckCircle2 size={40} color="#22C55E" />
                  ) : (
                    <AlertTriangle size={40} color={accuracyRate >= 70 ? '#F59E0B' : '#EF4444'} />
                  )}
                </View>
                <Text
                  className={cn(
                    'text-4xl font-bold',
                    accuracyRate >= 90
                      ? 'text-green-400'
                      : accuracyRate >= 70
                        ? 'text-amber-400'
                        : 'text-red-400'
                  )}
                >
                  {accuracyRate}%
                </Text>
                <Text className="text-slate-400 text-sm mt-1">Accuracy Rate</Text>
              </Animated.View>

              {/* Stats Grid */}
              <Animated.View
                entering={FadeInDown.duration(400).delay(100)}
                className="flex-row gap-3 mb-4"
              >
                <View className="flex-1 bg-slate-800/50 rounded-xl p-4 items-center">
                  <Package size={24} color="#3B82F6" />
                  <Text className="text-2xl font-bold text-white mt-2">{totalItems}</Text>
                  <Text className="text-slate-400 text-xs">Total Items</Text>
                </View>
                <View className="flex-1 bg-green-500/20 rounded-xl p-4 items-center">
                  <CheckCircle2 size={24} color="#22C55E" />
                  <Text className="text-2xl font-bold text-green-400 mt-2">
                    {matchedItems.length}
                  </Text>
                  <Text className="text-slate-400 text-xs">Matched</Text>
                </View>
              </Animated.View>

              {/* Variance Summary */}
              <Animated.View
                entering={FadeInDown.duration(400).delay(150)}
                className="bg-slate-800/50 rounded-2xl p-4 mb-4"
              >
                <View className="flex-row items-center mb-4">
                  <BarChart3 size={18} color="#A855F7" />
                  <Text className="text-white font-semibold ml-2">Variance Summary</Text>
                </View>

                {/* Short Items */}
                <View className="flex-row items-center justify-between py-3 border-b border-slate-700">
                  <View className="flex-row items-center">
                    <View className="w-8 h-8 rounded-full bg-red-500/20 items-center justify-center mr-3">
                      <TrendingDown size={16} color="#EF4444" />
                    </View>
                    <View>
                      <Text className="text-white font-medium">Short Items</Text>
                      <Text className="text-slate-400 text-xs">
                        {shortItems.length} items, {totalShortQty} units
                      </Text>
                    </View>
                  </View>
                  <Text className="text-red-400 font-bold">
                    -₹{totalShortValue.toLocaleString()}
                  </Text>
                </View>

                {/* Over Items */}
                <View className="flex-row items-center justify-between py-3 border-b border-slate-700">
                  <View className="flex-row items-center">
                    <View className="w-8 h-8 rounded-full bg-amber-500/20 items-center justify-center mr-3">
                      <TrendingUp size={16} color="#F59E0B" />
                    </View>
                    <View>
                      <Text className="text-white font-medium">Over Items</Text>
                      <Text className="text-slate-400 text-xs">
                        {overItems.length} items, {totalOverQty} units
                      </Text>
                    </View>
                  </View>
                  <Text className="text-amber-400 font-bold">
                    +₹{totalOverValue.toLocaleString()}
                  </Text>
                </View>

                {/* Net Variance */}
                <View className="flex-row items-center justify-between pt-3">
                  <Text className="text-white font-semibold">Net Variance</Text>
                  <Text
                    className={cn(
                      'text-xl font-bold',
                      netVarianceValue >= 0 ? 'text-amber-400' : 'text-red-400'
                    )}
                  >
                    {netVarianceValue >= 0 ? '+' : '-'}₹{Math.abs(netVarianceValue).toLocaleString()}
                  </Text>
                </View>
              </Animated.View>

              {/* Variance Details */}
              {hasIssues && (
                <Animated.View
                  entering={FadeInDown.duration(400).delay(200)}
                  className="bg-slate-800/50 rounded-2xl p-4 mb-4"
                >
                  <Text className="text-white font-semibold mb-3">Variance Details</Text>

                  {shortItems.length > 0 && (
                    <View className="mb-3">
                      <Text className="text-red-400 text-sm font-medium mb-2">
                        Short Items ({shortItems.length})
                      </Text>
                      {shortItems.slice(0, 5).map((entry) => (
                        <View
                          key={entry.id}
                          className="flex-row items-center justify-between py-2 border-b border-slate-700/50"
                        >
                          <View className="flex-1 mr-3">
                            <Text className="text-white text-sm" numberOfLines={1}>
                              {entry.itemName}
                            </Text>
                            <Text className="text-slate-400 text-xs">
                              System: {entry.systemStock} | Counted: {entry.countedQty}
                            </Text>
                          </View>
                          <View className="items-end">
                            <Text className="text-red-400 font-medium">{entry.variance}</Text>
                            <Text className="text-red-400/70 text-xs">
                              -₹{Math.abs(entry.varianceValue ?? 0).toLocaleString()}
                            </Text>
                          </View>
                        </View>
                      ))}
                      {shortItems.length > 5 && (
                        <Text className="text-slate-400 text-xs mt-2">
                          +{shortItems.length - 5} more items
                        </Text>
                      )}
                    </View>
                  )}

                  {overItems.length > 0 && (
                    <View>
                      <Text className="text-amber-400 text-sm font-medium mb-2">
                        Over Items ({overItems.length})
                      </Text>
                      {overItems.slice(0, 5).map((entry) => (
                        <View
                          key={entry.id}
                          className="flex-row items-center justify-between py-2 border-b border-slate-700/50"
                        >
                          <View className="flex-1 mr-3">
                            <Text className="text-white text-sm" numberOfLines={1}>
                              {entry.itemName}
                            </Text>
                            <Text className="text-slate-400 text-xs">
                              System: {entry.systemStock} | Counted: {entry.countedQty}
                            </Text>
                          </View>
                          <View className="items-end">
                            <Text className="text-amber-400 font-medium">+{entry.variance}</Text>
                            <Text className="text-amber-400/70 text-xs">
                              +₹{(entry.varianceValue ?? 0).toLocaleString()}
                            </Text>
                          </View>
                        </View>
                      ))}
                      {overItems.length > 5 && (
                        <Text className="text-slate-400 text-xs mt-2">
                          +{overItems.length - 5} more items
                        </Text>
                      )}
                    </View>
                  )}
                </Animated.View>
              )}

              {/* Action Buttons */}
              <Animated.View entering={FadeInUp.duration(400).delay(250)} className="gap-3">
                {/* Staff: Submit for Verification */}
                {user?.role === 'staff' && (
                  <Pressable
                    onPress={handleSubmitForVerification}
                    disabled={isSubmitting || totalItems === 0}
                    className={cn(
                      'py-4 rounded-2xl flex-row items-center justify-center',
                      isSubmitting || totalItems === 0
                        ? 'bg-slate-700'
                        : 'bg-blue-500 active:opacity-80'
                    )}
                  >
                    <Send size={20} color={isSubmitting || totalItems === 0 ? '#64748B' : '#fff'} />
                    <Text
                      className={cn(
                        'font-bold text-lg ml-2',
                        isSubmitting || totalItems === 0 ? 'text-slate-500' : 'text-white'
                      )}
                    >
                      {isSubmitting ? 'Submitting...' : 'Submit for Verification'}
                    </Text>
                  </Pressable>
                )}

                {/* Supervisor/Admin: Complete Session */}
                {(user?.role === 'supervisor' || user?.role === 'admin') && (
                  <Pressable
                    onPress={handleCompleteSession}
                    disabled={isSubmitting || totalItems === 0}
                    className={cn(
                      'py-4 rounded-2xl flex-row items-center justify-center',
                      isSubmitting || totalItems === 0
                        ? 'bg-slate-700'
                        : 'bg-green-500 active:opacity-80'
                    )}
                  >
                    <ClipboardCheck
                      size={20}
                      color={isSubmitting || totalItems === 0 ? '#64748B' : '#fff'}
                    />
                    <Text
                      className={cn(
                        'font-bold text-lg ml-2',
                        isSubmitting || totalItems === 0 ? 'text-slate-500' : 'text-white'
                      )}
                    >
                      {isSubmitting ? 'Completing...' : 'Complete Session'}
                    </Text>
                  </Pressable>
                )}

                {/* Continue Counting */}
                <Pressable
                  onPress={() => router.back()}
                  className="py-4 rounded-2xl bg-slate-700 items-center active:opacity-80"
                >
                  <Text className="text-white font-bold text-lg">Continue Counting</Text>
                </Pressable>
              </Animated.View>
            </View>
          </ScrollView>
        </SafeAreaView>
      </LinearGradient>
    </View>
  );
}
